version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ayoub007
      PGDATA: /data/postgres
      LISTEN_ADDRESSES: '*'
    volumes:
          - ./postgres-data:/var/lib/postgresql/data
          - ./init-db.sql:/docker-entrypoint-init-db.d/db.sql
    ports:
      - "8181:8181"
    restart: unless-stopped